# Generated by Django 4.1 on 2022-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Nombre', models.CharField(max_length=63, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('Fecha', models.IntegerField(verbose_name='Fecha')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
        ),
    ]
