# Generated by Django 4.1 on 2022-12-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='Precio',
            new_name='precio',
        ),
    ]
