# Generated by Django 4.1 on 2022-12-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_descripcion_venta_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10, verbose_name='Fecha')),
                ('detalle', models.CharField(max_length=30, verbose_name='Detalle')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(max_length=2, verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='TotalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
